### ISSUE TITLE
Mindmap support

### ISSUE THREAD

**Issue by WillieOng-HK** [FriendlyUser/vuepress-theme-cool-starter#11]
any mindmap diagram support? 
I tried PlantUML Mindmap but no luck

Thank you for the nice theme.

**Comment by FriendlyUser** [comment]
I can try to add it in.

Are you trying to include something like [vue-mindmap](https://codesandbox.io/s/jv7pl7wn15?ref=madewithvuejs.com)

**Comment by WillieOng-HK** [comment]
Thank you for the fast response!!
I just paste the following code which from plantuml mindmap
```
@startmindmap
* Debian
** Ubuntu
@endmindmap
```
but it shown the code, not diagram, is it confused with markdown syntax?

**Comment by FriendlyUser** [comment]
Can you try and see if the following code snippet works

```
@startuml
@startmindmap
caption figure 1
title My super title

* <&flag>Debian
** <&globe>Ubuntu
*** Linux Mint
*** Kubuntu
*** Lubuntu
*** KDE Neon
** <&graph>LMDE
** <&pulse>SolydXK
** <&people>SteamOS
** <&star>Raspbian with a very long name
*** <s>Raspmbc</s> => OSMC
*** <s>Raspyfi</s> => Volumio

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
@enduml
```

Seems to render on my computer

![image](https://user-images.githubusercontent.com/13860264/64502335-65f66380-d27a-11e9-9c58-4fad9b50ef44.png)

I believe that the plantuml plugin expects all plantuml code to be embedded with even for mindmaps.
```
@startuml

@enduml
```

**Comment by WillieOng-HK** [comment]
You are great!! It needs add the@startuml and @enduml tag before the mindmap tag, Thank you very much!
