### ISSUE TITLE
@vuepress/back-to-top not working

### ISSUE THREAD

**Issue by WillieOng-HK** [FriendlyUser/vuepress-theme-cool-starter#16]
how can it work on the back to top arrow?

**Comment by FriendlyUser** [comment]
I didn't install `@vuepress/plugin-back-to-top@next` or looks like the other last updated plugin..

See [plugin-back-to-top](https://v1.vuepress.vuejs.org/plugin/official/plugin-back-to-top.html) so the plugin is not there.

I'll add it into this starter theme when I have time.

To fix run:

```npm install --save-dev https://gridsome.org/starters/```

**Comment by FriendlyUser** [comment]
Looks like it the plugins are being applied in the latest build. See https://travis-ci.org/FriendlyUser/vuepress-theme-cool-starter/jobs/586824558

and back to top button is being display on the demo repo.

I personally couldn't get it working with globally installed vuepress, I believe for non-theme plugins they have run with locally installed vuepress.

`npm install --save vuepress`.
