### ISSUE TITLE
clone 之后 运行报错

### ISSUE THREAD

**Issue by evildoerX** [FriendlyUser/vuepress-theme-cool-starter#6]
![image](https://user-images.githubusercontent.com/14358159/62122336-0a8a9a80-b2f8-11e9-9d42-3af0bb1f2048.png)

提示缺少vuepress

全局安装vuepress之后
![image](https://user-images.githubusercontent.com/14358159/62122583-9c92a300-b2f8-11e9-9177-7e33a4733fd9.png)

非全局安装
![image](https://user-images.githubusercontent.com/14358159/62122815-2b9fbb00-b2f9-11e9-9fb5-882efc52fcb8.png)

![image](https://user-images.githubusercontent.com/14358159/62122842-38bcaa00-b2f9-11e9-9689-ebc099810b26.png)

安装下来的库并没有bin

**Comment by FriendlyUser** [comment]
你正在用吗 windows?

改成
```
  "scripts": {
    "docs:dev": "node node_modules/vuepress/cli.js dev docs",
    "docs:build": "node node_modules/vuepress/cli.js build docs",
    "dev": "vuepress dev docs",
    "build": "vuepress build docs"
  }
```
